/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WireframeRouteImport } from './routes/wireframe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PosRouteImport } from './routes/pos'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosIndexRouteImport } from './routes/pos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PosSettingsRouteImport } from './routes/pos.settings'
import { Route as PosProductsRouteImport } from './routes/pos.products'
import { Route as PosHistoryRouteImport } from './routes/pos.history'
import { Route as PosCategoriesRouteImport } from './routes/pos.categories'
import { Route as AdminUserRouteImport } from './routes/admin.user'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as AdminUserIndexRouteImport } from './routes/admin.user.index'
import { Route as AdminUserVolunteerRouteImport } from './routes/admin.user.volunteer'
import { Route as AdminUserReportsRouteImport } from './routes/admin.user.reports'
import { Route as AdminUserPesertaRouteImport } from './routes/admin.user.peserta'
import { Route as AdminUserEventsRouteImport } from './routes/admin.user.events'

const WireframeRoute = WireframeRouteImport.update({
  id: '/wireframe',
  path: '/wireframe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PosSettingsRoute = PosSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PosRoute,
} as any)
const PosProductsRoute = PosProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PosRoute,
} as any)
const PosHistoryRoute = PosHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PosRoute,
} as any)
const PosCategoriesRoute = PosCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PosRoute,
} as any)
const AdminUserRoute = AdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUserIndexRoute = AdminUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUserRoute,
} as any)
const AdminUserVolunteerRoute = AdminUserVolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => AdminUserRoute,
} as any)
const AdminUserReportsRoute = AdminUserReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminUserRoute,
} as any)
const AdminUserPesertaRoute = AdminUserPesertaRouteImport.update({
  id: '/peserta',
  path: '/peserta',
  getParentRoute: () => AdminUserRoute,
} as any)
const AdminUserEventsRoute = AdminUserEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminUserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/pos': typeof PosRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wireframe': typeof WireframeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/user': typeof AdminUserRouteWithChildren
  '/pos/categories': typeof PosCategoriesRoute
  '/pos/history': typeof PosHistoryRoute
  '/pos/products': typeof PosProductsRoute
  '/pos/settings': typeof PosSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/pos/': typeof PosIndexRoute
  '/admin/user/events': typeof AdminUserEventsRoute
  '/admin/user/peserta': typeof AdminUserPesertaRoute
  '/admin/user/reports': typeof AdminUserReportsRoute
  '/admin/user/volunteer': typeof AdminUserVolunteerRoute
  '/admin/user/': typeof AdminUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wireframe': typeof WireframeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/pos/categories': typeof PosCategoriesRoute
  '/pos/history': typeof PosHistoryRoute
  '/pos/products': typeof PosProductsRoute
  '/pos/settings': typeof PosSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/pos': typeof PosIndexRoute
  '/admin/user/events': typeof AdminUserEventsRoute
  '/admin/user/peserta': typeof AdminUserPesertaRoute
  '/admin/user/reports': typeof AdminUserReportsRoute
  '/admin/user/volunteer': typeof AdminUserVolunteerRoute
  '/admin/user': typeof AdminUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/pos': typeof PosRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wireframe': typeof WireframeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/user': typeof AdminUserRouteWithChildren
  '/pos/categories': typeof PosCategoriesRoute
  '/pos/history': typeof PosHistoryRoute
  '/pos/products': typeof PosProductsRoute
  '/pos/settings': typeof PosSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/pos/': typeof PosIndexRoute
  '/admin/user/events': typeof AdminUserEventsRoute
  '/admin/user/peserta': typeof AdminUserPesertaRoute
  '/admin/user/reports': typeof AdminUserReportsRoute
  '/admin/user/volunteer': typeof AdminUserVolunteerRoute
  '/admin/user/': typeof AdminUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/pos'
    | '/register'
    | '/reset-password'
    | '/wireframe'
    | '/admin/accounts'
    | '/admin/login'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/user'
    | '/pos/categories'
    | '/pos/history'
    | '/pos/products'
    | '/pos/settings'
    | '/admin/'
    | '/pos/'
    | '/admin/user/events'
    | '/admin/user/peserta'
    | '/admin/user/reports'
    | '/admin/user/volunteer'
    | '/admin/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/wireframe'
    | '/admin/accounts'
    | '/admin/login'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/pos/categories'
    | '/pos/history'
    | '/pos/products'
    | '/pos/settings'
    | '/admin'
    | '/pos'
    | '/admin/user/events'
    | '/admin/user/peserta'
    | '/admin/user/reports'
    | '/admin/user/volunteer'
    | '/admin/user'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/pos'
    | '/register'
    | '/reset-password'
    | '/wireframe'
    | '/admin/accounts'
    | '/admin/login'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/user'
    | '/pos/categories'
    | '/pos/history'
    | '/pos/products'
    | '/pos/settings'
    | '/admin/'
    | '/pos/'
    | '/admin/user/events'
    | '/admin/user/peserta'
    | '/admin/user/reports'
    | '/admin/user/volunteer'
    | '/admin/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PosRoute: typeof PosRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WireframeRoute: typeof WireframeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wireframe': {
      id: '/wireframe'
      path: '/wireframe'
      fullPath: '/wireframe'
      preLoaderRoute: typeof WireframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pos/settings': {
      id: '/pos/settings'
      path: '/settings'
      fullPath: '/pos/settings'
      preLoaderRoute: typeof PosSettingsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/products': {
      id: '/pos/products'
      path: '/products'
      fullPath: '/pos/products'
      preLoaderRoute: typeof PosProductsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/history': {
      id: '/pos/history'
      path: '/history'
      fullPath: '/pos/history'
      preLoaderRoute: typeof PosHistoryRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/categories': {
      id: '/pos/categories'
      path: '/categories'
      fullPath: '/pos/categories'
      preLoaderRoute: typeof PosCategoriesRouteImport
      parentRoute: typeof PosRoute
    }
    '/admin/user': {
      id: '/admin/user'
      path: '/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/user/': {
      id: '/admin/user/'
      path: '/'
      fullPath: '/admin/user/'
      preLoaderRoute: typeof AdminUserIndexRouteImport
      parentRoute: typeof AdminUserRoute
    }
    '/admin/user/volunteer': {
      id: '/admin/user/volunteer'
      path: '/volunteer'
      fullPath: '/admin/user/volunteer'
      preLoaderRoute: typeof AdminUserVolunteerRouteImport
      parentRoute: typeof AdminUserRoute
    }
    '/admin/user/reports': {
      id: '/admin/user/reports'
      path: '/reports'
      fullPath: '/admin/user/reports'
      preLoaderRoute: typeof AdminUserReportsRouteImport
      parentRoute: typeof AdminUserRoute
    }
    '/admin/user/peserta': {
      id: '/admin/user/peserta'
      path: '/peserta'
      fullPath: '/admin/user/peserta'
      preLoaderRoute: typeof AdminUserPesertaRouteImport
      parentRoute: typeof AdminUserRoute
    }
    '/admin/user/events': {
      id: '/admin/user/events'
      path: '/events'
      fullPath: '/admin/user/events'
      preLoaderRoute: typeof AdminUserEventsRouteImport
      parentRoute: typeof AdminUserRoute
    }
  }
}

interface AdminUserRouteChildren {
  AdminUserEventsRoute: typeof AdminUserEventsRoute
  AdminUserPesertaRoute: typeof AdminUserPesertaRoute
  AdminUserReportsRoute: typeof AdminUserReportsRoute
  AdminUserVolunteerRoute: typeof AdminUserVolunteerRoute
  AdminUserIndexRoute: typeof AdminUserIndexRoute
}

const AdminUserRouteChildren: AdminUserRouteChildren = {
  AdminUserEventsRoute: AdminUserEventsRoute,
  AdminUserPesertaRoute: AdminUserPesertaRoute,
  AdminUserReportsRoute: AdminUserReportsRoute,
  AdminUserVolunteerRoute: AdminUserVolunteerRoute,
  AdminUserIndexRoute: AdminUserIndexRoute,
}

const AdminUserRouteWithChildren = AdminUserRoute._addFileChildren(
  AdminUserRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUserRoute: typeof AdminUserRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUserRoute: AdminUserRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PosRouteChildren {
  PosCategoriesRoute: typeof PosCategoriesRoute
  PosHistoryRoute: typeof PosHistoryRoute
  PosProductsRoute: typeof PosProductsRoute
  PosSettingsRoute: typeof PosSettingsRoute
  PosIndexRoute: typeof PosIndexRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosCategoriesRoute: PosCategoriesRoute,
  PosHistoryRoute: PosHistoryRoute,
  PosProductsRoute: PosProductsRoute,
  PosSettingsRoute: PosSettingsRoute,
  PosIndexRoute: PosIndexRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PosRoute: PosRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WireframeRoute: WireframeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
